version: "3"

vars:
  APP_NAME: gin-gomp
  MAIN_FILE: cmd/main.go
  BIN_DIR: bin
  BIN_FILE: "{{.BIN_DIR}}/{{.APP_NAME}}"

tasks:

  # ============================================================
  # Default / Hilfe
  # ============================================================
  default:
    desc: Zeigt alle verfügbaren Tasks
    cmds:
      - task --list

  # ============================================================
  # Go Module & Qualität
  # ============================================================
  tidy:
    desc: Go modules aufräumen
    cmds:
      - go mod tidy

  test:
    desc: Go Tests ausführen
    cmds:
      - go test ./...

  # ============================================================
  # Konfiguration
  # ============================================================
  config:
    desc: Aktive Konfiguration ausgeben
    cmds:
      - go run {{.MAIN_FILE}} -config

  # ============================================================
  # Development
  # ============================================================
  dev:
    desc: Dev-Modus mit air (Hot Reload)
    cmds:
      - rm -rf tmp/
      - clear
      - air
    env:
      GO_ENV: development
      GIN_DEV: "true"

  # ============================================================
  # Build (lokal)
  # ============================================================
  build:
    desc: Binary bauen
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_FILE}} {{.MAIN_FILE}}

  # ============================================================
  # Build (Linux)
  # ============================================================
  build-linux:
    desc: Linux Binary bauen (amd64, static)
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - |
        CGO_ENABLED=0 \
        GOOS=linux \
        GOARCH=amd64 \
        go build -o {{.BIN_FILE}} {{.MAIN_FILE}}

  # ============================================================
  # Cleanup
  # ============================================================
  clean:
    desc: Build-Artefakte löschen
    cmds:
      - rm -rf {{.BIN_DIR}}
